### PR TITLE
checked attribute

### PR DESCRIPTION
**Pull request by netTrek**
Binding the checked attribute to checked die checkbox if value === true;

### CODE REVIEW

**Comment by udos86** [comment]
@netTrek Thank you very much, Saban, for your contribution! I'll merge it manually. After your first commit something seems to have gone wrong as Git states that all 271 have changed.

**Comment by netTrek** [comment]
Hi,

I've pushed my build by mistake.
SORRY

Regards
Saban

**Comment by udos86** [comment]
@netTrek Alright, no problem. Thanks again!

**Comment by netTrek** [comment]
@udos86  We should add the attribute for the other ui modules also.

**Comment by udos86** [comment]
@netTrek You're right. I'll do it.

**Comment by udos86** [comment]
@netTrek I cherry-picked your commit 88b40ee into development branch.

**Pull request closed without merging**
